version: '3.8'

services:
  chamber:
    build: .
    ports:
      - "8888:8888"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - CHAMBER_API_KEY=${CHAMBER_API_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./spell_archives:/app/spell_archives
volumes:
  spell_archives: