version: '3.8'

services:
  chamber:
    build: .
    ports:
      - "8888:8888"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - CHAMBER_API_KEY=${CHAMBER_API_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./src/chamber:/app/src/chamber
      - ./src/main.py:/app/src/main.py
      - ./src/requirements.txt:/app/src/requirements.txt
      - spell_archives:/app/archives
      - ./src/templates:/app/src/templates
      - ./src/static:/app/src/static
volumes:
  spell_archives: