version: '3.8'

services:
  chamber:
    build: .
    ports:
      - "8888:8888"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - CHAMBER_API_KEY=${CHAMBER_API_KEY}
    volumes:
      - ./src/chamber:/app/src/chamber
      - ./src/main.py:/app/src/main.py
      - ./src/requirements.txt:/app/src/requirements.txt
      - spell_archives:/app/archives

volumes:
  spell_archives: