name: Dev Chamber Deploy
on:
    push:
      branches-ignore:
        - main    # Triggers on pushes to any branch except main

jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      DEV_FLY_API_TOKEN: ${{ secrets.DEV_FLY_API_TOKEN }}
      CHAMBER_API_KEY: ${{ secrets.CHAMBER_API_KEY }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
    
    steps:
      # Your existing deployment steps, but targeting dev-chamber
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app dev-chamber