# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: Load environment variables
        run: |
          if [ -f .env ]; then
            echo "Loading environment variables..."
            export $(grep -v '^#' .env | xargs)
            echo "Environment variables loaded"
          fi
      - name: Set secrets on Fly.io
        run: |
          echo "Setting secrets on Fly.io..."
          flyctl secrets set \
            FLASK_SECRET_KEY="$FLASK_SECRET_KEY" \
            CHAMBER_API_KEY="$CHAMBER_API_KEY" \
            WEBHOOK_SECRET="$WEBHOOK_SECRET"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          CHAMBER_API_KEY: ${{ secrets.CHAMBER_API_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}

