name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy app
    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      CHAMBER_API_KEY: ${{ secrets.CHAMBER_API_KEY }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false  # Don't auto-checkout submodules
          
      - name: Update Submodules
        run: |
          # Remove existing submodule directory if it exists
          rm -rf src/grimoire
          
          # Reinitialize submodules from scratch
          git submodule init
          git submodule update
          
          # Enter grimoire directory and ensure we're up to date
          cd src/grimoire
          
          # Set up git config
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          # Fetch and checkout latest main
          git fetch origin main
          git checkout main
          git pull origin main
          
          # Return to root
          cd ../..
          
          # Update the parent repo's reference
          git add src/grimoire
          git commit -m "Update submodule to latest main" || echo "No changes to commit"

      - name: Load environment variables
        run: |
          if [ -f .env ]; then
            echo "Loading environment variables..."
            export $(grep -v '^#' .env | xargs)
            echo "Environment variables loaded"
          fi

      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Set secrets on Fly.io
        run: |
          echo "Setting secrets on Fly.io..."
          flyctl secrets set \
            FLASK_SECRET_KEY="$FLASK_SECRET_KEY" \
            CHAMBER_API_KEY="$CHAMBER_API_KEY" \
            WEBHOOK_SECRET="$WEBHOOK_SECRET"
            
      - run: flyctl deploy --remote-only