# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      CHAMBER_API_KEY: ${{ secrets.CHAMBER_API_KEY }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Add this to checkout submodules
          
      - name: Update submodules
        run: |
          git submodule update --remote --merge
          
      - name: Load environment variables
        run: |
          if [ -f .env ]; then
            echo "Loading environment variables..."
            export $(grep -v '^#' .env | xargs)
            echo "Environment variables loaded"
          fi
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set secrets on Fly.io
        run: |
          echo "Setting secrets on Fly.io..."
          flyctl secrets set \
            FLASK_SECRET_KEY="$FLASK_SECRET_KEY" \
            CHAMBER_API_KEY="$CHAMBER_API_KEY" \
            WEBHOOK_SECRET="$WEBHOOK_SECRET"
      - run: flyctl deploy --remote-only

